[build]
  command = "vite build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200